apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-requirements
data:
  requirements.txt: |
{{ .Values.requirements | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-starthooks
data:
  10-install-reqs.sh: |
    #!/bin/sh
    set -eu
    if [ -f /opt/requirements/requirements.txt ]; then
      echo "[startup] Installing deps from requirements.txt"
      # Don't fail the whole pod on pip hiccups:
      pip install --user -r /opt/requirements/requirements.txt || true
    else
      echo "[startup] No requirements.txt at /opt/requirements/requirements.txt"
    fi

